# Configuration for Basic ETL Pipeline

# Input/Output Configuration
input_file: "data/sales_data.csv"
output_file: "data/processed_sales.csv"
delimiter: ","
has_header: true

# Processing Configuration
threshold: 1000  # Filter values greater than this
sort_column: "amount"
sort_descending: true

# Optional: Additional transformations
# operations:
#   - type: "filter"
#     condition: "status == 'active'"
#   - type: "aggregate"
#     group_by: "category"
#     agg_func: "sum"