apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-registry
  namespace: mcp-platform
  labels:
    app: ai-registry
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-registry
  template:
    metadata:
      labels:
        app: ai-registry
        component: backend
    spec:
      containers:
      - name: ai-registry
        image: mcp/ai-registry:1.0.1
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MCP_SERVER_NAME
          value: "ai-registry"
        - name: MCP_PORT
          value: "8000"
        - name: MCP_LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ai-registry
  namespace: mcp-platform
spec:
  selector:
    app: ai-registry
  ports:
  - port: 8000
    targetPort: 8000
    name: http