apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: kailash-user-management
  labels:
    app: user-management
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_USER: dXNlcl9tZ21fdXNlcg==  # user_mgm_user
  DATABASE_PASSWORD: U2VjdXJlUGFzcw==  # SecurePass
  
  # Redis credentials
  REDIS_PASSWORD: UmVkaXNTZWNyZXQ=  # RedisSecret
  
  # JWT secrets
  JWT_SECRET_KEY: and1dF9zZWNyZXRfa2V5X3Zlcnlfc2VjdXJlXzIwMjQ=  # jwt_secret_key_very_secure_2024
  REFRESH_TOKEN_SECRET: cmVmcmVzaF90b2tlbl9zZWNyZXRfMjAyNA==  # refresh_token_secret_2024
  
  # Encryption keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfMzJfYnl0ZXNfbG9uZ18yMDI0  # encryption_key_32_bytes_long_2024
  
  # SMTP Configuration
  SMTP_USERNAME: c210cF91c2VybmFtZQ==  # smtp_username
  SMTP_PASSWORD: c210cF9wYXNzd29yZA==  # smtp_password
  
  # OAuth2 Configuration
  OAUTH2_CLIENT_SECRET: b2F1dGgyX2NsaWVudF9zZWNyZXRfMjAyNA==  # oauth2_client_secret_2024
  
  # MFA Configuration
  MFA_SECRET_KEY: bWZhX3NlY3JldF9rZXlfMjAyNA==  # mfa_secret_key_2024
  
  # API Keys
  ANALYTICS_API_KEY: YW5hbHl0aWNzX2FwaV9rZXlfMjAyNA==  # analytics_api_key_2024
  MONITORING_API_KEY: bW9uaXRvcmluZ19hcGlfa2V5XzIwMjQ=  # monitoring_api_key_2024

---
apiVersion: v1
kind: Secret
metadata:
  name: user-management-tls
  namespace: kailash-user-management
  labels:
    app: user-management
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # Certificate data
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...  # Private key data

---
# Secret for staging environment
apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: kailash-user-management-staging
  labels:
    app: user-management
    component: secrets
    environment: staging
type: Opaque
data:
  # Database credentials (base64 encoded) - staging
  DATABASE_USER: dXNlcl9tZ21fc3RhZ2luZw==  # user_mgm_staging
  DATABASE_PASSWORD: U3RhZ2luZ1Bhc3M=  # StagingPass
  
  # Redis credentials
  REDIS_PASSWORD: UmVkaXNTdGFnaW5n  # RedisStaging
  
  # JWT secrets
  JWT_SECRET_KEY: and1dF9zdGFnaW5nX3NlY3JldF9rZXk=  # jwt_staging_secret_key
  REFRESH_TOKEN_SECRET: cmVmcmVzaF9zdGFnaW5nX3Rva2Vu  # refresh_staging_token
  
  # Encryption keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9zdGFnaW5nX2tleQ==  # encryption_staging_key
  
  # SMTP Configuration
  SMTP_USERNAME: c210cF9zdGFnaW5n  # smtp_staging
  SMTP_PASSWORD: c210cF9zdGFnaW5nX3Bhc3M=  # smtp_staging_pass
  
  # OAuth2 Configuration
  OAUTH2_CLIENT_SECRET: b2F1dGgyX3N0YWdpbmdfc2VjcmV0  # oauth2_staging_secret
  
  # MFA Configuration
  MFA_SECRET_KEY: bWZhX3N0YWdpbmdfa2V5  # mfa_staging_key
  
  # API Keys
  ANALYTICS_API_KEY: YW5hbHl0aWNzX3N0YWdpbmc=  # analytics_staging
  MONITORING_API_KEY: bW9uaXRvcmluZ19zdGFnaW5n  # monitoring_staging

---
# Secret for development environment
apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: kailash-user-management-dev
  labels:
    app: user-management
    component: secrets
    environment: development
type: Opaque
data:
  # Database credentials (base64 encoded) - development
  DATABASE_USER: dXNlcl9tZ21fZGV2  # user_mgm_dev
  DATABASE_PASSWORD: RGV2UGFzcw==  # DevPass
  
  # Redis credentials
  REDIS_PASSWORD: UmVkaXNEZXY=  # RedisDev
  
  # JWT secrets
  JWT_SECRET_KEY: and1dF9kZXZfc2VjcmV0  # jwt_dev_secret
  REFRESH_TOKEN_SECRET: cmVmcmVzaF9kZXZfdG9rZW4=  # refresh_dev_token
  
  # Encryption keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9kZXZfa2V5  # encryption_dev_key
  
  # SMTP Configuration
  SMTP_USERNAME: c210cF9kZXY=  # smtp_dev
  SMTP_PASSWORD: c210cF9kZXZfcGFzcw==  # smtp_dev_pass
  
  # OAuth2 Configuration
  OAUTH2_CLIENT_SECRET: b2F1dGgyX2Rldl9zZWNyZXQ=  # oauth2_dev_secret
  
  # MFA Configuration
  MFA_SECRET_KEY: bWZhX2Rldl9rZXk=  # mfa_dev_key
  
  # API Keys
  ANALYTICS_API_KEY: YW5hbHl0aWNzX2Rldg==  # analytics_dev
  MONITORING_API_KEY: bW9uaXRvcmluZ19kZXY=  # monitoring_dev