---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nexus-postgres
  namespace: nexus-production
  labels:
    app: postgres
    component: database
spec:
  instances: 3

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      max_parallel_maintenance_workers: "4"

  # Primary update strategy
  primaryUpdateStrategy: unsupervised

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: nexus_prod
      owner: nexus
      secret:
        name: postgres-credentials

  # Storage configuration
  storage:
    size: 100Gi
    storageClass: fast-ssd

  # Monitoring
  monitoring:
    enabled: true

  # Backup configuration
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://nexus-backups/postgres"
      s3Credentials:
        accessKeyId:
          name: backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-credentials
          key: SECRET_ACCESS_KEY
      wal:
        retention: "5d"
      data:
        retention: "30d"

  # Resources
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  # Affinity rules
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: postgres
          topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: nexus-production
  labels:
    app: postgres
type: kubernetes.io/basic-auth
stringData:
  username: nexus
  password: changeme-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: nexus-production
  labels:
    app: postgres
    component: backup
type: Opaque
stringData:
  ACCESS_KEY_ID: "your-access-key-id"
  SECRET_ACCESS_KEY: "your-secret-access-key"
