---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-service-account
  namespace: nexus-production
  labels:
    app: nexus
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-role
  namespace: nexus-production
  labels:
    app: nexus
    environment: production
rules:
# Allow reading configmaps and secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading pod status for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow creating events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-role-binding
  namespace: nexus-production
  labels:
    app: nexus
    environment: production
subjects:
- kind: ServiceAccount
  name: nexus-service-account
  namespace: nexus-production
roleRef:
  kind: Role
  name: nexus-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-monitoring-service-account
  namespace: nexus-production
  labels:
    app: nexus
    component: monitoring
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-monitoring-role
  namespace: nexus-production
  labels:
    app: nexus
    component: monitoring
    environment: production
rules:
# Allow reading pods and services for service discovery
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading metrics
- apiGroups: [""]
  resources: ["pods/metrics"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-monitoring-role-binding
  namespace: nexus-production
  labels:
    app: nexus
    component: monitoring
    environment: production
subjects:
- kind: ServiceAccount
  name: nexus-monitoring-service-account
  namespace: nexus-production
roleRef:
  kind: Role
  name: nexus-monitoring-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-backup-service-account
  namespace: nexus-production
  labels:
    app: nexus
    component: backup
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-backup-role
  namespace: nexus-production
  labels:
    app: nexus
    component: backup
    environment: production
rules:
# Allow creating and managing backup jobs
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Allow reading persistent volumes for backup
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Allow reading secrets for backup credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-backup-role-binding
  namespace: nexus-production
  labels:
    app: nexus
    component: backup
    environment: production
subjects:
- kind: ServiceAccount
  name: nexus-backup-service-account
  namespace: nexus-production
roleRef:
  kind: Role
  name: nexus-backup-role
  apiGroup: rbac.authorization.k8s.io
