apiVersion: v2
name: mcp-platform
description: MCP Server Platform - Enterprise Gateway with Multiple Apps
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Integrum-Global/mcp_server
sources:
  - https://github.com/Integrum-Global/mcp_server
maintainers:
  - name: Integrum Team
    email: info@integrum.com

keywords:
  - mcp
  - ai
  - microservices
  - platform
  - gateway

dependencies:
  - name: user-management
    version: "1.0.0"
    repository: "file://charts/user-management"
    condition: user-management.enabled
  - name: ai-registry
    version: "1.0.1"
    repository: "file://charts/ai-registry"
    condition: ai-registry.enabled
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled