name: Check Documentation Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs-check.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip for template sync PRs
    if: |
      !(github.event.pull_request.user.login == 'github-actions[bot]' &&
        contains(github.event.pull_request.title, 'Sync template updates from'))
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install the package
        pip install -r docs/requirements.txt

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Check for warnings
      run: |
        cd docs
        # Fail if there are any warnings in the build
        make html 2>&1 | tee build.log
        if grep -q "WARNING" build.log; then
          echo "Documentation build contains warnings"
          exit 1
        fi
