name: Sync from Template

on:
  # Manual trigger only - no automatic syncs
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create PR (true) or just show diff (false)'
        required: false
        type: boolean
        default: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull template updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMPLATE_REPO: Integrum-Global/new_project_template
        run: |
          # Add template as remote
          git remote add template https://github.com/${TEMPLATE_REPO}.git || true
          git fetch template main
          
          # Create sync branch
          BRANCH_NAME="template-sync-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          
          # Get list of files to sync from template
          SYNC_FILES=(
            # SDK guidance - sync specific subdirectories only
            "sdk-users/api"
            "sdk-users/developer" 
            "sdk-users/essentials"
            "sdk-users/features"
            "sdk-users/instructions"
            "sdk-users/nodes"
            "sdk-users/patterns"
            "sdk-users/templates"
            "sdk-users/workflows"
            "sdk-users/CLAUDE.md"
            "sdk-users/README.md"
            "sdk-users/validation-guide.md"
          )
          
          # Files to sync only if missing (preserve existing)
          SYNC_IF_MISSING=(
            # Root files - create if missing but don't overwrite
            "README.md"
            "pyproject.toml"
            "CHANGELOG.md"
            
            # Project-specific directories - sync all content if directory missing
            "adr"
            "prd" 
            "mistakes"
            "todos"
            "migrations"
            "data"
            "docs"
            "examples"
            "src/solutions"
          )
          
          # Files that need special merge handling
          MERGE_FILES=(
            "CLAUDE.md"
          )
          
          # Directories that should be merged (add new, preserve existing)
          MERGE_DIRS=(
            "src/shared"
            "scripts"
          )
          
          # Sync each file/directory (always overwrite)
          for item in "${SYNC_FILES[@]}"; do
            if git ls-tree template/main --name-only | grep -q "^$item"; then
              git checkout template/main -- "$item" 2>/dev/null || true
            fi
          done
          
          # Sync files/directories only if they don't exist (preserve existing)
          for item in "${SYNC_IF_MISSING[@]}"; do
            if git ls-tree template/main --name-only | grep -q "^$item" && [ ! -e "$item" ]; then
              echo "Syncing missing item: $item"
              git checkout template/main -- "$item" 2>/dev/null || true
              # If it's a directory, sync all its contents recursively
              if [ -d "$item" ]; then
                git checkout template/main -- "$item/**" 2>/dev/null || true
              fi
            fi
          done
          
          # Handle files that need merging
          for item in "${MERGE_FILES[@]}"; do
            if git ls-tree template/main --name-only | grep -q "^$item"; then
              if [ -e "$item" ]; then
                # File exists, need to merge
                echo "Merging $item..."
                
                # Get the template version
                git show template/main:"$item" > "${item}.template"
                
                # For CLAUDE.md, preserve project-specific instructions
                if grep -q "## Project-Specific Instructions" "$item"; then
                  # Extract project-specific section
                  sed -n '/## Project-Specific Instructions/,$p' "$item" > "${item}.project"
                  
                  # Check if template already has project-specific section
                  if ! grep -q "## Project-Specific Instructions" "${item}.template"; then
                    # Append project section to template
                    cat "${item}.template" > "$item"
                    echo "" >> "$item"
                    cat "${item}.project" >> "$item"
                  else
                    # Template already has the section, just use template version
                    cp "${item}.template" "$item"
                  fi
                  rm -f "${item}.project"
                else
                  # No project-specific section, use template version
                  cp "${item}.template" "$item"
                fi
                
                rm -f "${item}.template"
              else
                # File doesn't exist, just sync from template
                git checkout template/main -- "$item" 2>/dev/null || true
              fi
            fi
          done
          
          # Handle directories that need merging (add new files, preserve existing)
          for item in "${MERGE_DIRS[@]}"; do
            if git ls-tree template/main --name-only | grep -q "^$item"; then
              echo "Merging directory: $item"
              # Get new files from template without overwriting existing ones
              git checkout template/main -- "$item" 2>/dev/null || true
            fi
          done
          
          # Check if there are changes
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Sync template updates from ${TEMPLATE_REPO} - Automated sync at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            
            # Push and create PR
            git push origin HEAD
            
            gh pr create \
              --title "Sync template updates" \
              --body "Automated template sync from ${TEMPLATE_REPO} at $(date -u +%Y-%m-%dT%H:%M:%SZ). Synced sdk-users/ (SDK reference) and CLAUDE.md. Project-specific content preserved: adr/, prd/, mistakes/, todos/, migrations/, docs/, src/solutions/. Please review changes.

Note: This is a template sync PR - CI tests are automatically skipped." \
              --base main
          else
            echo "No changes to sync"
          fi