name: Template Sync Check

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  # Quick check for template sync PRs only
  template-sync-check:
    name: Template Sync Validation
    # Only run on PRs created by the template sync process
    if: |
      contains(github.event.pull_request.title, 'Sync template updates') ||
      contains(github.event.pull_request.title, 'template sync') ||
      contains(github.event.pull_request.title, 'Template sync') ||
      startsWith(github.event.pull_request.head.ref, 'template-sync-') ||
      contains(github.event.pull_request.body, 'Automated template sync from') ||
      contains(github.event.pull_request.body, 'This PR automatically syncs updates from the template repository') ||
      contains(github.event.pull_request.body, 'This updates sdk-users/, CLAUDE.md, GitHub workflows') ||
      contains(github.event.pull_request.body, '## Template Sync') ||
      contains(github.event.pull_request.body, 'Full CI pipeline is skipped for template sync PRs')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Basic syntax check
      run: |
        # Just check Python files can be parsed
        find . -name "*.py" -type f -exec python -m py_compile {} \;

    - name: Check critical files exist
      run: |
        # Ensure critical files weren't accidentally removed
        test -f pyproject.toml
        test -f README.md
        test -f CLAUDE.md
        test -d .github/workflows/
        
        # Check for template structure (apps/ may not exist in fresh repos)
        if [ -d "apps" ]; then
          echo "✅ Apps directory exists"
          if [ -d "apps/_template" ]; then
            echo "✅ App template structure exists"
          fi
        else
          echo "ℹ️ Apps directory not yet created"
        fi
        
        # Check SDK users documentation was synced
        if [ -d "sdk-users" ]; then
          echo "✅ SDK users documentation synced"
        else
          echo "❌ SDK users documentation missing"
          exit 1
        fi

    - name: Post success comment
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: '✅ **Template Sync Validation Passed!**\n\nThis PR contains template updates that:\n- ✅ Update SDK documentation and workflows\n- ✅ Preserve all your client code and customizations\n- ✅ Add missing template structure only\n\n**No full CI needed** - lightweight validation completed successfully. Your project-specific code remains untouched! 🛡️'
          });
